baseURL = "https://cranky-archimedes-30cb02.netlify.app/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring-light"
title = "Area51 Designs"
[markup.goldmark.renderer]
unsafe = true
